ALTER TABLE "user"
	ADD COLUMN user_type TEXT NOT NULL DEFAULT 'SIMPLE_USER',
	ADD COLUMN passport TEXT,
	ADD COLUMN INN TEXT,
	ADD COLUMN OGRNIP TEXT,
	ADD COLUMN OGRN TEXT,
	ADD COLUMN KPP TEXT,
	ADD COLUMN company_name TEXT,
	ADD COLUMN BIK TEXT,
	ADD COLUMN correspondent_account TEXT,
	ADD COLUMN payment_account TEXT;
