INSERT INTO brand(name) VALUES
	('GRAVITEIGHT'),
	('A LA RUSSE'),
	('LOUIS VUITTON'),
	('CHRISTIAN DIOR'),
	('CHANEL'),
	('HALE BOB'),
	('ZILLI'),
	('STEFANO RICCI'),
	('MARIA GRAZIA SEVERI'),
	('MAXIME SIMOENS'),
	('VDP')
